num1=int(input("enter first number: "))
num2=int(input("enter second number: "))
print("sum: ",num1+num2)
print("subtraction: ",num1-num2)
print("product: ",num1*num2)
print("division: ",num1/num2)